name: GambitTesting
author: opd02
version: 2.2.3
main: me.opd02.gambittesting.Main
depend: [TitleAPI, WorldEdit]
commands:
  resetbanks:
  start:
  gearup:
  stopgame:
  bluespawnfreeze:
  redspawnfreeze:
  token: